// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfi-Rf0h5EQff-vqduZaKcPsuSbXKap-g',
    appId: '1:217133625875:web:561b1cf37345d74bcb05e6',
    messagingSenderId: '217133625875',
    projectId: 'flutterapplication01-c0557',
    authDomain: 'flutterapplication01-c0557.firebaseapp.com',
    storageBucket: 'flutterapplication01-c0557.appspot.com',
    measurementId: 'G-9SMY2MXSVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbc19E084Yd-k_IQ79HC5lmceJmlE12q4',
    appId: '1:217133625875:android:8dd57720478dfcf0cb05e6',
    messagingSenderId: '217133625875',
    projectId: 'flutterapplication01-c0557',
    storageBucket: 'flutterapplication01-c0557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjhzs7TuxHlbN0oV7pmUrjQPNY_ORGzY',
    appId: '1:217133625875:ios:6d9194a916282d52cb05e6',
    messagingSenderId: '217133625875',
    projectId: 'flutterapplication01-c0557',
    storageBucket: 'flutterapplication01-c0557.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqjhzs7TuxHlbN0oV7pmUrjQPNY_ORGzY',
    appId: '1:217133625875:ios:6d9194a916282d52cb05e6',
    messagingSenderId: '217133625875',
    projectId: 'flutterapplication01-c0557',
    storageBucket: 'flutterapplication01-c0557.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
